### ISSUE TITLE
Close dosnt work

### ISSUE THREAD

**Issue by noxsii** [WadeShuler/laravel-flashmessages#2]
The Click on the Close Icon dosnt work :( Any Solution?

**Comment by WadeShuler** [comment]
@noxsii Sorry, just now seeing this. It looks like I assumed someone using Tailwind would have Apline installed, and Bootstrap their JS files.

There isn't a great way to handle the JS options since everyone will have a different use case. So it probably should have been documented.

If Bootstrap, install your version's javascript files. If using Tailwind or anything else, you can use Apline, Vue, or any other JS framework, or write your own pure javascript, to handle the closing of the messages.

For someone not using Bootstrap, I would use the Tailwind view files as a starting point and modify as needed.
